export default [
  {
    id: 1,
    x: 25,
    y: 15,
    breed: "HUMAIN",
    type: "Neutre",
    size: "Moyen",
    intelligence: "Moyenne",
    element: "",
    habitat: "Cité antique",
    alignment: "Neutre",
    lifespan: "Mortel",
    pictureUrl: "./creatures/humains.png"
  },
  {
    id: 2,
    x: 15,
    y: 75,
    breed: "ELFE",
    type: "Magique",
    size: "Moyen",
    intelligence: "Élevée",
    element: "./logos/lumiere.png",
    habitat: "Cité antique",
    alignment: "Bon",
    lifespan: "Élevée",
    pictureUrl: "./creatures/elfes.jpg"
  },
  {
    id: 3,
    x: 80,
    y:68,
    breed: "FEE",
    type: "Magique",
    size: "Minuscule",
    intelligence: "Élevée",
    element: "./logos/air.png",
    habitat: "Forêt",
    alignment: "Bon",
    lifespan: "Élevée",
    pictureUrl: "./creatures/fees.jpg"
  },
  {
    id: 4,
    x: 90,
    y: 20,
    breed: "ORC",
    type: "Guerrier",
    size: "Grand",
    intelligence: "Basique",
    element: "./logos/terre.png",
    habitat: "Montagne",
    alignment: "Mauvais",
    lifespan: "Mortel",
    pictureUrl: "./creatures/orcs.jpg"
  },
  {
    id: 5,
    x: 10,
    y: 45,
    breed: "NYMPHE",
    type: "Divin",
    size: "Moyen",
    intelligence: "Élevée",
    element: "./logos/feuille.png",
    habitat: "Foret",
    alignment: "Neutre",
    lifespan: "Élevée",
    pictureUrl: "./creatures/nymphes.png"
  },
  {
    id: 6,
    x: 15,
    y: 25,
    breed: "DRAGON",
    type: "Divin",
    size: "Colossal",
    intelligence: "Divine",
    element: "./logos/air.png",
    habitat: "Montagne",
    alignment: "Bon",
    lifespan: "Immortel",
    pictureUrl: "./creatures/dragons.jpg"
  },
  {
    id: 7,
    x: 30,
    y: 75,
    breed: "GOBELIN",
    type: "Malicieux",
    size: "Petit",
    intelligence: "Basique",
    element: "./logos/terre.png",
    habitat: "Souterrain",
    alignment: "Mauvais",
    lifespan: "Mortel",
    pictureUrl: "./creatures/gobelins.jpg"
  },
  {
    id: 8,
    x: 45,
    y: 35,
    breed: "NAIN",
    type: "Guerrier",
    size: "Petit",
    intelligence: "Moyenne",
    element: "./logos/terre.png",
    habitat: "Montagne",
    alignment: "Neutre",
    lifespan: "Élevée",
    pictureUrl: "./creatures/nains.jpg"
  },
  {
    id: 9,
    x: 10,
    y: 90,
    breed: "CHLOROPHILIEN",
    type: "Magique",
    size: "Grand",
    intelligence: "Basique",
    element: "./logos/feuille.png",
    habitat: "Forêt",
    alignment: "Neutre",
    lifespan: "Élevée",
    pictureUrl: "./creatures/chlorophiliens.jpg"
  },
  {
    id: 10,
    x: 75,
    y: 95,
    breed: "GOLEM",
    type: "G-ardien",
    size: "Géant",
    intelligence: "Basique",
    element: "./logos/terre.png",
    habitat: "Cité antique",
    alignment: "Neutre",
    lifespan: "Immortel",
    pictureUrl: "./creatures/golems.jpg"
  },
  {
    id: 10,
    x: 75,
    y: 55,
    breed: "SIRENE",
    type: "Neutre",
    size: "Moyen",
    intelligence: "Moyenne",
    element: "./logos/eau.png",
    habitat: "Océan",
    alignment: "Mauvais",
    lifespan: "Mortel",
    pictureUrl: "./creatures/sirenes.jpg"
  }
]
